services:
  - type: web
    name: redmine
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: REDMINE_DB_MYSQL
        value: mysql.railway.internal
      - key: REDMINE_DB_DATABASE
        value: redmine
      - key: REDMINE_DB_USERNAME
        value: root
      - key: REDMINE_DB_PASSWORD
        value: KxCtmLXmTAPxILbrfLoVECxjCUXNtEno
